### ISSUE TITLE
Bug involving downloads / configs

### ISSUE THREAD

**Issue by Cyclicz** [CompVis/stable-diffusion#248]
I've been messing around with stable-diffusion for a few days now. It's been quite amazing what it's capable of! It's been very reliable but today after trying to generate a prompt I see it download a file out of nowhere and then proceed to throw a fatal error shortly afterwards. It now refuses to generate anything else and keeps throwing the same error. Normally I'd trace it further myself, but I'm not very familiar with this codebase as of yet. I'll submit a copy of the terminal output below and keep around a copy of the broken version in case you have any specific questions. I'm running this on Debian and all the rest of the relevant information to get acquainted should be in the terminal output below.

```(ldm) ┌──(ilak㉿TRITON)-[~/stable-diffusion]
└─$ python scripts/txt2img.py --prompt "a monkey riding a bike in the city" --plms --ckpt sd-v1-4.ckpt --skip_grid --n_samples 1 --seed 34 
Global seed set to 34
Loading model from sd-v1-4.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.42k/4.42k [00:00<00:00, 1.73MB/s]
Traceback (most recent call last):
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/configuration_utils.py", line 650, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/configuration_utils.py", line 734, in _dict_from_json_file
    return json.loads(text)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/txt2img.py", line 361, in <module>
    main()
  File "scripts/txt2img.py", line 257, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 54, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/ilak/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/ilak/stable-diffusion/ldm/models/diffusion/ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/ilak/stable-diffusion/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/ilak/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/ilak/stable-diffusion/ldm/modules/encoders/modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ilak/miniconda3/envs/ldm/lib/python3.8/site-packages/transformers/configuration_utils.py", line 652, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/home/ilak/.cache/huggingface/transformers/9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.```

**Comment by lmxyy** [comment]
I also met this error suddenly today.

**Comment by exixx** [comment]
I had this pop up midway through a set of runs where all I changed was one parameter.

**Comment by simulanics** [comment]
Seeing the same...

Loading model from ../../models/stable-diffusion-1.4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Traceback (most recent call last):
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\configuration_utils.py", line 650, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\configuration_utils.py", line 734, in _dict_from_json_file
    return json.loads(text)
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew\Desktop\STABLE~1.0\Data\repo\OPTIMI~1\OPTIMI~2.PY", line 218, in <module>
    modelCS = instantiate_from_config(config.modelCondStage)
  File "c:\users\matthew\desktop\stablediffusiongui-v1.3.0\data\repo\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "c:\users\matthew\desktop\stablediffusiongui-v1.3.0\data\repo\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "c:\users\matthew\desktop\stablediffusiongui-v1.3.0\data\repo\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "c:\users\matthew\desktop\stablediffusiongui-v1.3.0\data\repo\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "c:\users\matthew\desktop\stablediffusiongui-v1.3.0\data\repo\ldm\modules\encoders\modules.py", line 248, in __init__
    self.transformer = CLIPTextModel.from_pretrained(
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Matthew\Desktop\StableDiffusionGui-v1.3.0\Data\mb\envs\ldo\lib\site-packages\transformers\configuration_utils.py", line 652, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'C:\Users\Matthew/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.

Confirmed. Started 20 minutes ago. Tried deleting the cache folder and new base files are downloaded from huggingfaces. Prompts the same errors.

**Comment by macCesar** [comment]
I've finished installing it on my M1 Mac mini.. and I'm having the same errors!!

**Comment by simulanics** [comment]
***The issue appears to be in the downloaded files coming from huggingfaces directly. If you have a working copy of stable diffusion, it will remain to function so as long as it doesn't re-establish an internet connection at this point in time. Permitting updated configs to be downloaded will result in failed image generation.

**Comment by aunymoons** [comment]
Does anyone have a working copy of the old configs? having this issue as of today as well all of the sudden.

**Comment by Cyclicz** [comment]
Is there a related pull-request of some sort on the recent huggingfaces release?

**Comment by simulanics** [comment]
Quick fix :-)

Open the file in question - find:


This can be worked around in the meantime by manually editing the file in question and removing two trailing commas in two dict objects (one on line 87, one on line 169)

Which file? Could you please share a snippet from the lines in question? Thanks beforehand

It will be in the file listed after:
OSError: It looks like the config file at

You'll see an unneeded comma at 87 and 169 like:
"num_hidden_layers": 12, "projection_dim": 768, },

Remove it:
"num_hidden_layers": 12, "projection_dim": 768 },

**Run the JSON thru a JSON validator to find the issues if you cannot find them.

**Comment by aunymoons** [comment]
Just noticed mine is complaining about the exact same file so that kinda corroborates that its an issue with the downloaded config.
```
raise EnvironmentError(
OSError: It looks like the config file at 'C:\Users\Aunym/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.
```

**Comment by simulanics** [comment]
Fixed Contents:

`{
	"_name_or_path": "clip-vit-large-patch14/",
	"architectures": [
		"CLIPModel"
	],
	"initializer_factor": 1.0,
	"logit_scale_init_value": 2.6592,
	"model_type": "clip",
	"projection_dim": 768,
	"text_config": {
		"_name_or_path": "",
		"add_cross_attention": false,
		"architectures": null,
		"attention_dropout": 0.0,
		"bad_words_ids": null,
		"bos_token_id": 0,
		"chunk_size_feed_forward": 0,
		"cross_attention_hidden_size": null,
		"decoder_start_token_id": null,
		"diversity_penalty": 0.0,
		"do_sample": false,
		"dropout": 0.0,
		"early_stopping": false,
		"encoder_no_repeat_ngram_size": 0,
		"eos_token_id": 2,
		"finetuning_task": null,
		"forced_bos_token_id": null,
		"forced_eos_token_id": null,
		"hidden_act": "quick_gelu",
		"hidden_size": 768,
		"id2label": {
			"0": "LABEL_0",
			"1": "LABEL_1"
		},
		"initializer_factor": 1.0,
		"initializer_range": 0.02,
		"intermediate_size": 3072,
		"is_decoder": false,
		"is_encoder_decoder": false,
		"label2id": {
			"LABEL_0": 0,
			"LABEL_1": 1
		},
		"layer_norm_eps": 1e-05,
		"length_penalty": 1.0,
		"max_length": 20,
		"max_position_embeddings": 77,
		"min_length": 0,
		"model_type": "clip_text_model",
		"no_repeat_ngram_size": 0,
		"num_attention_heads": 12,
		"num_beam_groups": 1,
		"num_beams": 1,
		"num_hidden_layers": 12,
		"num_return_sequences": 1,
		"output_attentions": false,
		"output_hidden_states": false,
		"output_scores": false,
		"pad_token_id": 1,
		"prefix": null,
		"problem_type": null,
		"projection_dim": 768,
		"pruned_heads": {},
		"remove_invalid_values": false,
		"repetition_penalty": 1.0,
		"return_dict": true,
		"return_dict_in_generate": false,
		"sep_token_id": null,
		"task_specific_params": null,
		"temperature": 1.0,
		"tie_encoder_decoder": false,
		"tie_word_embeddings": true,
		"tokenizer_class": null,
		"top_k": 50,
		"top_p": 1.0,
		"torch_dtype": null,
		"torchscript": false,
		"transformers_version": "4.16.0.dev0",
		"use_bfloat16": false,
		"vocab_size": 49408
	},
	"text_config_dict": {
		"hidden_size": 768,
		"intermediate_size": 3072,
		"num_attention_heads": 12,
		"num_hidden_layers": 12,
		"projection_dim": 768
	},
	"torch_dtype": "float32",
	"transformers_version": null,
	"vision_config": {
		"_name_or_path": "",
		"add_cross_attention": false,
		"architectures": null,
		"attention_dropout": 0.0,
		"bad_words_ids": null,
		"bos_token_id": null,
		"chunk_size_feed_forward": 0,
		"cross_attention_hidden_size": null,
		"decoder_start_token_id": null,
		"diversity_penalty": 0.0,
		"do_sample": false,
		"dropout": 0.0,
		"early_stopping": false,
		"encoder_no_repeat_ngram_size": 0,
		"eos_token_id": null,
		"finetuning_task": null,
		"forced_bos_token_id": null,
		"forced_eos_token_id": null,
		"hidden_act": "quick_gelu",
		"hidden_size": 1024,
		"id2label": {
			"0": "LABEL_0",
			"1": "LABEL_1"
		},
		"image_size": 224,
		"initializer_factor": 1.0,
		"initializer_range": 0.02,
		"intermediate_size": 4096,
		"is_decoder": false,
		"is_encoder_decoder": false,
		"label2id": {
			"LABEL_0": 0,
			"LABEL_1": 1
		},
		"layer_norm_eps": 1e-05,
		"length_penalty": 1.0,
		"max_length": 20,
		"min_length": 0,
		"model_type": "clip_vision_model",
		"no_repeat_ngram_size": 0,
		"num_attention_heads": 16,
		"num_beam_groups": 1,
		"num_beams": 1,
		"num_hidden_layers": 24,
		"num_return_sequences": 1,
		"output_attentions": false,
		"output_hidden_states": false,
		"output_scores": false,
		"pad_token_id": null,
		"patch_size": 14,
		"prefix": null,
		"problem_type": null,
		"projection_dim": 768,
		"pruned_heads": {},
		"remove_invalid_values": false,
		"repetition_penalty": 1.0,
		"return_dict": true,
		"return_dict_in_generate": false,
		"sep_token_id": null,
		"task_specific_params": null,
		"temperature": 1.0,
		"tie_encoder_decoder": false,
		"tie_word_embeddings": true,
		"tokenizer_class": null,
		"top_k": 50,
		"top_p": 1.0,
		"torch_dtype": null,
		"torchscript": false,
		"transformers_version": "4.16.0.dev0",
		"use_bfloat16": false
	},
	"vision_config_dict": {
		"hidden_size": 1024,
		"intermediate_size": 4096,
		"num_attention_heads": 16,
		"num_hidden_layers": 24,
		"patch_size": 14,
		"projection_dim": 768
	}
}`

**Comment by simulanics** [comment]
> ```
>     raise EnvironmentError(
> OSError: It looks like the config file at '/home/jward/.cache/huggingface/transformers/9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.
> ```
> 
> I literally just came here to post this -- removing the trailing `,` after `projection_dim` - in my file, it was in two places. Presumably someone's modifying JSON with a text-replace.
> 
> Separately, it's extremely annoying that an app in a local repo would suddenly stop working 💥 . I get it, dependencies, updates, yadda yadda. It just shouldn't do that - perhaps lock down your dependencies?

On a positive note that this issue has occurred - I'm adding an error checker to our Babelfish Stable Diffusion Dream Studio to check the cache files before attempting to generate an image, and correct any bad JSON 👍

**Comment by Cyclicz** [comment]
> 

Again, I'm not personally involved in this repository so these are somewhat blind suggestions, but what if the issue is more than just bad JSON? Maybe have it download the new file, keep the old one. If the new file tries to run and fails it temporarily defaults back to the old one? There's gotta be a better solution here. Again, I have 0 knowledge of how releases work for these files.

**Comment by aunymoons** [comment]
@simulanics Thank you for that suggestion, indeed it works as a workaround ^^

**Comment by simulanics** [comment]
> 

Stable Diffusion attempts to check for any new/updated weights before generating an image and technically doesn't need to. You could comment the weight checking code to bypass checking upon each image generation. 

If you have no need to visit huggingfaces.co, you can also open your system hosts file and add:

`
127.0.0.1   huggingfaces.co
`

**This will block stable diffusion from connecting to huggingfaces and immediately drop the connection.

In my case, I need any updated weights available, so my best bet is to allow the check, and verify the json downloaded is correct before saving - otherwise fix it, then save :-)

**Comment by Cyclicz** [comment]
> **This will block stable diffusion from connecting to huggingfaces and immediately drop the connection.
Information like this could certainly belong in the weights section of the readme

**Comment by JakeBlockchain** [comment]
@simulanics What file are we editing exactly? 
New to coding so I can't fully grasp what is what.

**Comment by Cyclicz** [comment]
> 
You're editing the one here listed at the bottom of your error:
```like the config file at 'C:\Users\Matthew/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.```

There are a few extra commas on line 87 and 169 that may need removing.
I assume they'll be working on a fix shortly for everyone who doesn't know how to edit the files directly.

**Comment by Lime-Cakes** [comment]
Issue and solution are https://github.com/huggingface/transformers/issues/18965
Just wait a bit if you don't know how to fed working cache in. Clean model should be online soon

**Comment by simulanics** [comment]
The file will be located at:

c:\Users\YOURUSERNAME\.cache\huggingface\transformers\

and the filename you will need to obtain from the very last line of the error message after:

OSError: It looks like the config file at "Filename.json" is invalid.

In our case - the filename is:
9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142

**Comment by vltmedia** [comment]
Luckily cached stuff from a few days ago still work!

Here's a zip of pretrained configs from 09/02/2022 that will help get through the error: 
[stable-diffusion_PretrainedConfigs_20220902.zip](https://www.dropbox.com/s/cs95hybhynbatio/stable-diffusion_PretrainedConfigs_20220902.zip?dl=0)

Extract it somewhere and use that directory as the ```cache_dir``` for the transformer.

To skip downloading and force the usage of the downloaded files, update ```ldm\modules\encoders\modules.py``` Line 144 from:
``` python
self.transformer = CLIPTextModel.from_pretrained(version).to(device)
```
To this. Which now includes the path to where you extracted the contents of the zip file. (Replace ```F:/ai/pretrained``` with your directory):
``` python
self.transformer = CLIPTextModel.from_pretrained(version,local_files_only = True, force_download = False, cache_dir ='F:/ai/pretrained' ).to(device)
```

Don't forget to revert back if needed when this ultimately fixed.

**Comment by Cyclicz** [comment]
I think there's enough work done / solutions provided to close this issue. Thanks y'all and happy generating!

**Comment by manugarri** [comment]
@vltmedia doesnt seem to work, i still get the same issue even though i can navigate to the cache dir from the same  file it loads the model at.

**Comment by Cyclicz** [comment]
Would've thought this would be fully resolved by now. For the moment, did you reference the solutions that simulanics provided?

> Quick fix :-)
> 
> This can be worked around in the meantime by manually editing the file in question and removing two trailing commas in two dict objects (one on line 87, one on line 169)
> 
> You'll see an unneeded comma at 87 and 169 like: "num_hidden_layers": 12, "projection_dim": 768, },
> 
> Remove it: "num_hidden_layers": 12, "projection_dim": 768 },
> 
> **Run the JSON thru a JSON validator to find the issues if you cannot find them.

**Comment by manugarri** [comment]
Well, im actually experiencing the issue with this [other Google collab](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb) for Stable diffusion textual inversion.  

Cant seem to load the text_encoder for the CLipModel and I tried your solution 

>self.transformer = CLIPTextModel.from_pretrained(version, local_files_only = True, force_download = False, cache_dir ='ai/pretrained' ).to(device)

Out of curiosity, is this a temporary issue with HF model serving?

**Comment by Cyclicz** [comment]
At least with stable-diffusion it is/was. There's a supposed pull request [here](https://github.com/huggingface/transformers/pull/18964) but I'm not fully certain on the status of everything on that end. They added an extra comma or two in the JSON where it shouldn't have been and downloaded updates are forced by default. It downloaded the faulty file and then failed to read it.

The fix that ended up working for most of us is the one I mentioned last post.
Your error may be slightly different though. Did you get the same/similar output as what was listed here?
You can supposedly turn off these updates via another method mentioned by simulanics:


> > 
> 
> Stable Diffusion attempts to check for any new/updated weights before generating an image and technically doesn't need to. You could comment the weight checking code to bypass checking upon each image generation.
> 
> If you have no need to visit huggingfaces.co, you can also open your system hosts file and add:
> 
> `127.0.0.1 huggingfaces.co`
> 
> **This will block stable diffusion from connecting to huggingfaces and immediately drop the connection.
> 
> In my case, I need any updated weights available, so my best bet is to allow the check, and verify the json downloaded is correct before saving - otherwise fix it, then save :-)

**Comment by manugarri** [comment]
Thanks for the info. Actually now that I check, the error happens when running this code:

```
text_encoder = CLIPTextModel.from_pretrained(
    'CompVis/stable-diffusion-v1-4', subfolder="text_encoder", use_auth_token=True
)
```

And the error is different

```
OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named config.json.
```

So yeah, I misread the issue and tried  running the suggested local caching but that did not fix it unfortunately. Anyway my issue is not related to this bug, my apologies.

**Comment by XavierXiao** [comment]
@manugarri Did you solve the issue of `OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named config.json.`? I had the same issue.
